import localFont from 'next/font/local';
import './globals.scss';
import Navbar from './components/Navbar';

const hemingSans = localFont({
  src: './fonts/Heming.ttf',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={hemingSans.className}>
        <Navbar />
        <main className='main-content'>{children}</main>
      </body>
    </html>
  );
}
