import localFont from 'next/font/local';
import './globals.scss';
import Navbar from './components/Navbar';
import dynamic from 'next/dynamic';

const hemingSans = localFont({
  src: './fonts/Heming.ttf',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={hemingSans.className}>
        <AnimatedCursor
          innerSize={5}
          outerSize={30}
          color='200,200,200'
          outerAlpha={0.3}
          innerScale={0.7}
          outerScale={1.3}
          trailingSpeed={5}
          outerStyle={{
            border: '2px solid var(--cursor-color)',
          }}
          innerStyle={{
            backgroundColor: 'var(--cursor-color)',
          }}
        />
        <Navbar />
        <main className='main-content'>{children}</main>
      </body>
    </html>
  );
}
